#!/usr/bin/env bash
# Generate an embedded test JPEG as a C header (for proving the decode->display path
# before SD-card loading exists). Reproducible; run in WSL/Linux.
# Usage: ./tools/gen_test_asset.sh <output_header.h>
set -euo pipefail

OUT="${1:?usage: gen_test_asset.sh <output_header.h>}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Colorful pattern -> baseline JPEG (sized to the photo-frame area).
ppmpat -madras -width 480 -height 288 > "$TMP/test.ppm" 2>/dev/null \
    || ppmpat -madras 480 288 > "$TMP/test.ppm"
cjpeg -quality 85 -baseline "$TMP/test.ppm" > "$TMP/test.jpg"

# Emit a C header with a const byte array.
xxd -i -n lumen_test_jpg "$TMP/test.jpg" > "$TMP/raw.h"
{
    echo "// Generated by tools/gen_test_asset.sh — embedded baseline JPEG for the decode demo."
    echo "#pragma once"
    sed 's/^unsigned char/const unsigned char/; s/^unsigned int/const unsigned int/' "$TMP/raw.h"
} > "$OUT"

echo "wrote $OUT (jpeg $(stat -c%s "$TMP/test.jpg") bytes)"
